#!/usr/bin/env python3
"""ÍSDAL — static site generator.

Generates all HTML pages (shared header/footer + content) into the repo root.
Run:  python3 build.py
"""

import os

ROOT = os.path.dirname(os.path.abspath(__file__))

WEDGE = '<svg width="{s}" height="{s}" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><polygon points="0,9 24,0 24,24 0,24"/></svg>'

FAVICON = (
    "data:image/svg+xml,"
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E"
    "%3Cpolygon points='0,9 24,0 24,24 0,24' fill='%23131311'/%3E%3C/svg%3E"
)

SITE = "https://www.isdal.is"
OG_IMAGE = f"{SITE}/assets/img/og-cover.png"  # generated by make_cover.py

INSTAGRAM = "https://www.instagram.com/hildur_isdal/"
LINKEDIN = "https://www.linkedin.com/in/hildur-%C3%ADsdal-316766318/"
MBL_LAUGARDALUR = "https://www.mbl.is/smartland/heimili/2025/11/18/hildur_hannadi_storkostlegt_eldhus_i_reykjavik/"
MBL_MOSFELLSBAER = "https://www.mbl.is/smartland/heimili/2025/02/23/bogadreginn_tangi_kom_i_stadinn_fyrir_eyju/"
DISTRICTHIVE = "https://districthive.com/prospectus_iceland.html"


def head(title, desc, p, url):
    return f"""<!DOCTYPE html>
<html lang="is">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<meta name="theme-color" content="#f1efea">
<meta property="og:site_name" content="ÍSDAL — Arkitektúr &amp; innanhússhönnun">
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{OG_IMAGE}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="ÍSDAL — Architecture &amp; Interior">
<meta property="og:locale" content="is_IS">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="{FAVICON}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{p}css/style.css">
</head>
<body>"""


def header(p, current):
    def cur(name):
        return ' aria-current="page"' if name == current else ""

    return f"""
<header class="site-header">
  <div class="wrap bar">
    <a class="logo" href="{p}index.html" aria-label="ÍSDAL — forsíða">
      {WEDGE.format(s=26)}
      <span class="word">ÍSDAL</span>
      <span class="tag">Architecture<br>&amp; Interior</span>
    </a>
    <button class="menu-btn" aria-expanded="false" aria-controls="nav">Valmynd</button>
    <nav class="site-nav" id="nav">
      <a href="{p}verkefni.html"{cur('verkefni')}>Verkefni</a>
      <a href="{p}um-okkur.html"{cur('um')}>Um okkur</a>
      <a href="{p}frettir.html"{cur('frettir')}>Fréttir</a>
      <a href="{p}hafa-samband.html"{cur('samband')}>Hafa samband</a>
    </nav>
  </div>
</header>"""


def footer(p):
    return f"""
<footer class="site-footer">
  <div class="wrap">
    <div class="cols">
      <div>
        <span class="label">Stofan</span>
        <p class="blurb">Ísdal er arkitekta- og hönnunarstofa í Reykjavík sem vinnur þvert á arkitektúr og innanhússhönnun — frá fyrstu skissu að fullbúnu rými.</p>
      </div>
      <div>
        <span class="label">Vefur</span>
        <ul>
          <li><a href="{p}verkefni.html">Verkefni</a></li>
          <li><a href="{p}um-okkur.html">Um okkur</a></li>
          <li><a href="{p}frettir.html">Fréttir</a></li>
          <li><a href="{p}hafa-samband.html">Hafa samband</a></li>
        </ul>
      </div>
      <div>
        <span class="label">Samfélagsmiðlar</span>
        <ul>
          <li><a href="{INSTAGRAM}" target="_blank" rel="noopener">Instagram</a></li>
          <li><a href="{LINKEDIN}" target="_blank" rel="noopener">LinkedIn</a></li>
        </ul>
      </div>
      <div>
        <span class="label">Hafa samband</span>
        <ul>
          <li><a href="mailto:info@isdal.is">info@isdal.is</a></li>
          <li>Austurstræti 12a</li>
          <li>101 Reykjavík, Ísland</li>
        </ul>
      </div>
    </div>
    <div class="footer-mark">
      <div class="word">ÍSDAL</div>
      <div class="fine">© 2026 Ísdal ehf.<br>Architecture &amp; Interior</div>
    </div>
  </div>
</footer>
<script src="{p}js/main.js"></script>
</body>
</html>"""


def page(filename, title, desc, current, body, p=""):
    url = SITE + ("/" if filename == "index.html" else "/" + filename)
    html = head(title, desc, p, url) + header(p, current) + body + footer(p)
    path = os.path.join(ROOT, filename)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    print("wrote", filename)


# ------------------------------------------------------------------
# project data
#
# The first four projects are Ísdal's own, fully designed by the studio,
# and are featured on the front page. Everything after them is a
# "fyrra verkefni" — work Hildur contributed to at other firms before
# Ísdal was founded; those are clearly attributed.
# ------------------------------------------------------------------

PROJECTS = [
    {
        "slug": "sumarhus-vid-geysi",
        "num": "01",
        "title": "Sumarhús við Geysi",
        "cat": "arkitektur",
        "catlabel": "Arkitektúr",
        "card": "geysir-1.webp",
        "meta": [
            ("Staðsetning", "Haukadalur, Bláskógabyggð"),
            ("Tegund", "Sumarhús — nýbygging"),
            ("Hlutverk", "Arkitektúr og innanhússhönnun"),
            ("Ár", "2024–"),
            ("Staða", "Í byggingu"),
        ],
        "lede": "Sumarhús hannað utan um norðurljósin og útsýnið yfir Haukadal — svart timburhús sem hvílir lágt í mosavöxnu hrauni.",
        "paras": [
            "Húsið er hugsað sem sjónauki að himni og fjallahring. Brotið mænisform opnar stór gluggafleti til norðurs og upp í rjáfur, þannig að norðurljósin verða hluti af stofunni á veturna og miðnætursólin á sumrin. Svört standandi klæðning lætur húsið hverfa inn í dökkt hraunið á meðan hlý birta innan úr því lýsir eins og lugt í landslaginu.",
            "Innra skipulagið er einfalt og hagkvæmt: samfellt alrými fyrir eldhús, borðstofu og stofu undir fullri lofthæð, svefnrými á tveimur pöllum og baðstofa sem tengist heitum potti á sólpalli. Efnisvalið er fábrotið — náttúrulegur viður, steinn og ull — valið til að eldast fallega með húsinu.",
            "Verkefnið er unnið alla leið frá fyrstu skissu að byggingarleyfi og eftirliti á framkvæmdatíma.",
        ],
        "figs": [
            ("geysir-1.webp", "Húsið að vetri — norðurljós yfir Haukadal", False),
            ("geysir-2.webp", "Suðurhlið — svört klæðning í mosavöxnu hrauni", False),
        ],
    },
    {
        "slug": "skerdingsstadir",
        "num": "02",
        "title": "Skerðingsstaðir — District Hive",
        "cat": "arkitektur",
        "catlabel": "Arkitektúr — skipulag",
        "card": "skerdingsstadir-1.jpg",
        "meta": [
            ("Staðsetning", "Skerðingsstaðir við Grundarfjörð, Snæfellsnesi"),
            ("Tegund", "Heilsudvöl — 14 dvalarklefar"),
            ("Hlutverk", "Heildarskipulag svæðis"),
            ("Verkkaupi", "District Hive"),
            ("Ár", "2025–"),
            ("Staða", "Í hönnun — áætluð opnun 2026"),
            ("Vefur", f'<a href="{DISTRICTHIVE}" target="_blank" rel="noopener">districthive.com ↗</a>'),
        ],
        "lede": "Heildarskipulag heilsudvalar á Snæfellsnesi — fjórtán speglaðir dvalarklefar raðast í geislamynstur innblásið af íslenskum galdrastöfum, með sjónás beint á Kirkjufell.",
        "paras": [
            "Á 7,4 hektara landi Skerðingsstaða vestan Grundarfjarðar er horft yfir Breiðafjörð og til Vestfjarða. Skipulagið tekur mið af staðnum í einu og öllu: fornminjar bæjarhólsins mynda miðju svæðisins, klefarnir raðast um hann í geislamynstri og einn skýr ás liggur í gegnum hólinn beint á Kirkjufell við sjóndeildarhringinn. Um 98% landsins er haldið óröskuðu sem engi og verndarsvæði.",
            "Gist er í fjórtán speglaðum GlassHive-dvalarklefum fyrir tvo, þar sem landslagið speglast í klefunum á daginn og stjörnuhiminninn vakir yfir gestum á nóttunni. Á svæðinu eru einnig heit laug, gufuböð, gróðurhús og skjólgarður hlaðinn úr grjóti sem myndar verndandi boga til suðurs — efnisval sem sækir í basalt og búskaparminjar staðarins.",
            "Ísdal vinnur heildarskipulag svæðisins fyrir District Hive og er verkefnið í hönnun; áætluð opnun er í lok árs 2026.",
        ],
        "figs": [
            ("skerdingsstadir-1.jpg", "GlassHive-dvalarklefi að kvöldi", False),
            ("skerdingsstadir-plan.jpg", "Heildarskipulag — geislamynstur um bæjarhólinn, ás á Kirkjufell", False),
            ("skerdingsstadir-2.jpg", "Landslagið speglast í klefunum", True),
            ("skerdingsstadir-3.jpg", "Staðurinn — horft yfir kyrran fjörðinn", True),
        ],
    },
    {
        "slug": "eldhus-i-laugardal",
        "num": "03",
        "title": "Eldhús í Laugardal",
        "cat": "innanhus",
        "catlabel": "Innanhússhönnun",
        "card": "eldhus-laug-1.webp",
        "meta": [
            ("Staðsetning", "Laugardalur, Reykjavík"),
            ("Tegund", "Eldhús og borðstofa"),
            ("Hlutverk", "Innanhússhönnun"),
            ("Ár", "2025"),
            ("Staða", "Lokið"),
            ("Umfjöllun", f'<a href="{MBL_LAUGARDALUR}" target="_blank" rel="noopener">mbl.is — nóv. 2025 ↗</a>'),
        ],
        "lede": "Eldhús í húsi frá 1985, teiknuðu af Kjartani Sveinssyni — dökkur viður og hvítyrjóttur steinn ofan á upprunalegum bleikum marmara sem fékk að halda sér.",
        "paras": [
            "Eldhúsinu var upprunalega skipt í þrjú rými — eldhús, borðkrók og fína borðstofu. Þegar milliveggir voru farnir stóð eftir eitt stórt og langt rými, opinn strigi fyrir nýja innréttingu. Áskorunin lá í gólfinu: bleiki marmarinn er upprunalegur og var slípaður og bónaður í stað þess að hrófla við honum, svo hvorki vatn né rafmagn var fært að ráði.",
            "Innréttingin er teiknuð frá gólfi í loft: heilklæddur tækjaveggur með innfelldum ofnum og kaffihorni losar vinnufleti eyjunnar, og tangi við eyjuna nýtist jafnt sem matar- og vinnuborð, baðaður dagsbirtu. Borðplatan er hvítyrjótt og höfð einföld svo gólfefnið fái að njóta sín. Búrið var endurgert, hurðagat breikkað og rennihurð sett í.",
            "Við matarborðið var sérhannaður glasaskápur með innfelldri lýsingu sem rammar inn borðhaldið og heldur heildarsvip í gegnum bæði rými.",
        ],
        "figs": [
            ("eldhus-laug-1.webp", "Eldhúsið — dökkur viður og hvítyrjóttur steinn", False),
            ("eldhus-laug-4.jpg", "Tanginn á eyjunni — matar- og vinnuborð í dagsbirtu", True),
            ("eldhus-laug-2.webp", "Borðkrókurinn við gluggann", True),
            ("eldhus-laug-3.webp", "Sérhannaður glasaskápur við matarborðið", True),
            ("eldhus-laug-5.jpg", "Búrið — endurgert með rennihurð", True),
            ("eldhus-laug-6.jpg", "Húsið frá 1985, teiknað af Kjartani Sveinssyni", False),
        ],
    },
    {
        "slug": "eldhus-i-mosfellsbae",
        "num": "04",
        "title": "Eldhús í Mosfellsbæ",
        "cat": "innanhus",
        "catlabel": "Innanhússhönnun",
        "card": "eldhus-mos-1.webp",
        "meta": [
            ("Staðsetning", "Mosfellsbær"),
            ("Tegund", "Eldhús"),
            ("Hlutverk", "Innanhússhönnun"),
            ("Ár", "2024"),
            ("Staða", "Lokið"),
            ("Umfjöllun", f'<a href="{MBL_MOSFELLSBAER}" target="_blank" rel="noopener">mbl.is — feb. 2025 ↗</a>'),
        ],
        "lede": "Langt og mjótt eldhús þar sem bogadreginn tangi kom í staðinn fyrir eyju — klassísk hönnun og praktík í senn, með marmara sem flæðir upp á veggi.",
        "paras": [
            "Rýmið var langt og mjótt og hefðbundin eyja hefði þrengt að því. Í staðinn var settur bogadreginn tangi við enda innréttingarinnar — fimm manneskjur geta setið við hann og hann tengir eldhúsið við garðinn og dagsbirtuna. Rifflaður eikarviður og ávöl form gera tangann að húsgagni frekar en innréttingu.",
            "Marmarinn setur tóninn: hann liggur á borðflötum, heldur áfram sem heill bakveggur og flæðir upp á veggi inni í kaffihorninu sem prýðir innréttinguna. Hvítar sléttar hurðir halda heildinni rólegri en hlýjan kemur úr viðnum og látúnsdetaljum í tækjum og höldum.",
            "Verkefnið var eitt af fyrstu verkum stofunnar og sameinar það sem eigendur báðu um: praktík hversdagsins og klassíska hönnun sem eldist vel.",
        ],
        "figs": [
            ("eldhus-mos-1.webp", "Bogadregni tanginn — rifflaður eikarviður og marmari", False),
            ("eldhus-mos-3.jpg", "Langt og mjótt rými — tanginn við enda innréttingarinnar", True),
            ("eldhus-mos-2.webp", "Kaffihornið — marmarinn flæðir upp á veggi", True),
            ("eldhus-mos-4.jpg", "Hátt til lofts og útgengt í garðinn", False),
        ],
    },
    # ---------- fyrri verkefni — unnin hjá öðrum stofum fyrir stofnun Ísdal ----------
    {
        "slug": "rvk-studios",
        "num": "05",
        "title": "RVK Studios",
        "cat": "fyrri",
        "catlabel": "Fyrra verk",
        "card": "rvk-studios-2.webp",
        "meta": [
            ("Staðsetning", "Gufunes, Reykjavík"),
            ("Tegund", "Endurgerð iðnaðarhúsnæðis"),
            ("Hlutverk", "Hönnun vinnurýma og sameigna"),
            ("Stofa", "Fyrra verk — unnið fyrir stofnun Ísdal"),
            ("Ár", "2023"),
            ("Staða", "Lokið"),
        ],
        "lede": "Gömul áburðarverksmiðja í Gufunesi fékk nýtt líf sem kvikmyndaver og skrifstofur RVK Studios.",
        "paras": [
            "Hráleiki verksmiðjunnar fékk að halda sér: steypt burðarvirki, sýnilegar lagnir og veðrað timbur mynda bakgrunn fyrir nýja starfsemi. Nýjum innskotum — fundarherbergjum, mötuneyti og vinnustofum — er komið fyrir sem frístandandi einingum inni í stóra rýminu svo saga hússins er alltaf sýnileg.",
            "Mötuneytið og sameiginleg rými liggja að opnu gengi umhverfis miðjukjarna, þar sem dagsbirta að ofan flæðir niður í gegnum hæðirnar. Húsgögn og lýsing voru valin til að standast harða notkun kvikmyndaframleiðslu án þess að missa hlýju.",
            "Verkefnið var unnið áður en Ísdal var stofnuð.",
        ],
        "figs": [
            ("rvk-studios-2.webp", "Mötuneyti og samverurými í gömlu verksmiðjunni", False),
            ("rvk-studios-1.webp", "Yfirlitsmynd — kvikmyndaverið í Gufunesi", False),
        ],
    },
    {
        "slug": "fjolbyli-med-inngardi",
        "num": "06",
        "title": "Fjölbýli með inngarði",
        "cat": "fyrri",
        "catlabel": "Fyrra verk",
        "card": "fjolbyli-1.webp",
        "meta": [
            ("Staðsetning", "Höfuðborgarsvæðið"),
            ("Tegund", "Íbúðir — hönnunartillaga"),
            ("Hlutverk", "Arkitektúr"),
            ("Stofa", "Fyrra verk — unnið fyrir stofnun Ísdal"),
            ("Ár", "2024"),
            ("Staða", "Tillaga"),
        ],
        "lede": "Tillaga að timburbyggðu fjölbýli þar sem íbúðirnar raðast um gróinn inngarð — sameign sem raunverulega er notuð.",
        "paras": [
            "Byggingin er brotin upp í smærri einingar með svölum og gróðurhúsum sem snúa inn í garðinn, þannig að hvert heimili á sér bæði skjólgóða einkaverönd og hlutdeild í sameiginlegu útirými. Inngarðurinn er hannaður sem dvalarsvæði með tjörn, matjurtabeðum og leiksvæði — hversdagslegur fundarstaður íbúa.",
            "Burðarvirki og klæðningar eru úr timbri til að lágmarka kolefnisspor, og virk jarðhæð með bakaríi og smáverslun tengir húsið við götuna.",
        ],
        "figs": [
            ("fjolbyli-1.webp", "Inngarðurinn — tjörn og dvalarsvæði", False),
            ("fjolbyli-2.webp", "Götuhlið með virkri jarðhæð", False),
        ],
    },
    {
        "slug": "albano",
        "num": "07",
        "title": "Albano háskólasvæðið",
        "cat": "fyrri",
        "catlabel": "Fyrra verk — Arkitema",
        "card": "albano-1.webp",
        "meta": [
            ("Staðsetning", "Stokkhólmur, Svíþjóð"),
            ("Tegund", "Háskólasvæði"),
            ("Stofa", "Arkitema — Hildur í verkefnateymi"),
            ("Ár", "2017–2021"),
            ("Staða", "Lokið"),
        ],
        "lede": "Nýtt háskólahverfi fyrir Stokkhólmsháskóla og KTH — kennsluhús, rannsóknarrými og stúdentaíbúðir í vistvottuðu borgarumhverfi.",
        "paras": [
            "Albano er eitt stærsta uppbyggingarverkefni háskólanna í Stokkhólmi og var skipulagt sem „vistkerfishverfi“ þar sem byggingar, almenningsrými og gróður vinna saman. Hildur starfaði að verkefninu sem arkitekt hjá Arkitema, meðal annars að hönnun kennslu- og rannsóknarbygginga.",
            "Verkefnið kenndi margt sem fylgir stofunni enn: samhæfingu stórra hagsmunahópa, sjálfbærnivottanir og hvernig almannarými á milli húsa ráða jafnmiklu um upplifun og húsin sjálf.",
        ],
        "figs": [
            ("albano-1.webp", "Háskólahverfið við Brunnsviken", False),
            ("albano-2.webp", "Kennslubyggingar og almenningsrými", False),
        ],
    },
    {
        "slug": "langsjoskolan",
        "num": "08",
        "title": "Långsjöskolan",
        "cat": "fyrri",
        "catlabel": "Fyrra verk — Arkitema",
        "card": "langsjo-1.webp",
        "meta": [
            ("Staðsetning", "Stokkhólmur, Svíþjóð"),
            ("Tegund", "Grunnskóli — 900 nemendur"),
            ("Stofa", "Arkitema — Hildur í verkefnateymi"),
            ("Ár", "2022"),
            ("Staða", "Lokið"),
        ],
        "lede": "Grunnskóli fyrir 900 nemendur þar sem timburklæðning, dagsbirta og skýr innri skipan mynda rólegan skóladag.",
        "paras": [
            "Skólinn er skipulagður um heimasvæði árganga — smærri einingar innan stórrar byggingar sem gefa nemendum öryggi og yfirsýn. Kennslurými opnast að sameiginlegum torgum þar sem hópvinna og frjáls leikur fá pláss.",
            "Timbur er ráðandi efni jafnt úti sem inni og skólalóðin var hönnuð samhliða húsinu svo útikennsla og hreyfing fléttast inn í daglegt starf. Hildur vann að verkefninu sem arkitekt hjá Arkitema.",
        ],
        "figs": [
            ("langsjo-1.webp", "Aðkoman — timburklæddar álmur", False),
            ("langsjo-2.webp", "Skólalóðin", True),
            ("langsjo-3.webp", "Heimasvæði árganga", True),
        ],
    },
    {
        "slug": "grunnskoli-i-nykoping",
        "num": "09",
        "title": "Grunnskóli í Nyköping",
        "cat": "fyrri",
        "catlabel": "Fyrra verk — Cedervall",
        "card": "nykoping-1.webp",
        "meta": [
            ("Staðsetning", "Nyköping, Svíþjóð"),
            ("Tegund", "Grunnskóli — 1.100 nemendur"),
            ("Stofa", "Cedervall arkitekter — Hildur í verkefnateymi"),
            ("Ár", "2017"),
            ("Staða", "Lokið"),
        ],
        "lede": "Einn stærsti grunnskóli Svíþjóðar á sínum tíma — 1.100 nemendur undir einu þaki án þess að nokkur týnist.",
        "paras": [
            "Lykillinn að svo stórum skóla er að brjóta hann niður í læsilegar einingar: aðgreindar álmur með eigin inngöngum og heimasvæðum raðast um sameiginlegan miðkjarna með sal, bókasafni og mötuneyti. Þannig fær hver nemandi „lítinn skóla“ innan þess stóra.",
            "Hildur vann að verkefninu hjá Cedervall arkitekter, frá forhönnun að útboðsgögnum.",
        ],
        "figs": [
            ("nykoping-1.webp", "Skólinn í Nyköping", False),
        ],
    },
]


def pcard(pr, p, eager=False):
    load = "" if eager else ' loading="lazy"'
    return f"""
      <a class="pcard reveal" href="{p}verkefni/{pr['slug']}.html" data-cat="{pr['cat']}">
        <div class="frame"><img src="{p}assets/img/{pr['card']}" alt="{pr['title']}"{load}></div>
        <div class="meta">
          <span class="num">{pr['num']}</span>
          <span class="title-line">{pr['title']}</span>
          <span class="cat">{pr['catlabel']}</span>
        </div>
      </a>"""


# ------------------------------------------------------------------
# index.html
# ------------------------------------------------------------------

featured = PROJECTS[:4]

hero_slides = "".join(
    f'\n        <img class="slide{" is-active" if i == 0 else ""}" src="assets/img/{pr["card"]}" alt="{pr["title"]}"{"" if i == 0 else " loading=\"lazy\""}>'
    for i, pr in enumerate(featured)
)
hero_dots = "".join(
    f'\n        <button type="button"{" class=\"active\"" if i == 0 else ""} aria-label="Mynd {i + 1} — {pr["title"]}"></button>'
    for i, pr in enumerate(featured)
)

index_body = f"""
<main>
  <section class="hero wrap">
    <span class="label"><b>Ísdal</b> — Arkitektúr &amp; innanhússhönnun</span>
    <h1 class="display">Rými sem eiga rætur í&nbsp;stað, birtu og&nbsp;fólki</h1>
    <div class="hero-grid">
      <div>
        <p class="lede">Ísdal er arkitekta- og hönnunarstofa í Reykjavík sem vinnur þvert á arkitektúr og innanhússhönnun. Með yfir tuttugu ára reynslu af heimilum, skrifstofum og almenningsbyggingum fylgjum við verkefnum alla leið — frá fyrstu skissu að byggingarleyfi og fullbúnu rými.</p>
        <br>
        <a class="alink" href="verkefni.html">Skoða verkefnin</a>
      </div>
      <div class="hero-carousel reveal" aria-label="Verkefni Ísdal">
        <div class="slides">{hero_slides}
        </div>
        <div class="dots" role="group" aria-label="Velja mynd">{hero_dots}
        </div>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <div class="section-head">
        <span class="label">01 — <b>Verkefni Ísdal</b></span>
        <a class="alink" href="verkefni.html">Öll verkefni</a>
      </div>
      <div class="projects-grid">
        {''.join(pcard(pr, '') for pr in featured)}
      </div>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <div class="section-head">
        <span class="label">02 — <b>Þjónusta</b></span>
      </div>
      <div class="services">
        <div class="service-row reveal">
          <span class="num">/01</span>
          <h3>Arkitektúr</h3>
          <p>Nýbyggingar, viðbyggingar og endurgerð eldri húsa — íbúðarhús, sumarhús og almenningsbyggingar, frá frumhugmynd að fullbúnu húsi.</p>
        </div>
        <div class="service-row reveal">
          <span class="num">/02</span>
          <h3>Innanhússhönnun</h3>
          <p>Innréttingar, efnisval, lýsing og húsgögn. Við teiknum sérsmíði niður í minnstu detalju og fylgjum framleiðslu og uppsetningu eftir.</p>
        </div>
        <div class="service-row reveal">
          <span class="num">/03</span>
          <h3>Vinnustaðir</h3>
          <p>Skrifstofur, mötuneyti og sérhæfð vinnurými. Greining á þörfum, rýmisskipulag og hönnun sem styður ólíkar vinnustundir dagsins.</p>
        </div>
        <div class="service-row reveal">
          <span class="num">/04</span>
          <h3>Byggingarleyfi &amp; ráðgjöf</h3>
          <p>Aðaluppdrættir, byggingarleyfisumsóknir og samskipti við byggingarfulltrúa — við þekkjum ferlið og styttum leiðina.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <div class="section-head">
        <span class="label">03 — <b>Stofan</b></span>
        <a class="alink" href="um-okkur.html">Um okkur</a>
      </div>
      <p class="lede">Ísdal var stofnuð af Hildi Ísdal, arkitekt og innanhússhönnuði. Stofan leggur áherslu á náttúrleg efni, birtu og tímalausa hönnun — rými sköpuð utan um fólkið sem notar þau, með gæði út í gegn.</p>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <div class="section-head">
        <span class="label">04 — <b>Fréttir</b></span>
        <a class="alink" href="frettir.html">Allar fréttir</a>
      </div>
      <div class="news-list">
        <a class="news-item reveal" href="frettir.html">
          <time datetime="2026-08-01">01.08.2026</time>
          <h3>Ný ásýnd og nýr vefur Ísdal</h3>
          <span class="arrow">→</span>
        </a>
        <a class="news-item reveal" href="frettir.html">
          <time datetime="2026-06-15">15.06.2026</time>
          <h3>Sara innanhússhönnuður gengur til liðs við stofuna</h3>
          <span class="arrow">→</span>
        </a>
        <a class="news-item reveal" href="frettir.html">
          <time datetime="2026-03-10">10.03.2026</time>
          <h3>Ísdal opnar vinnustofu á Austurstræti 12a</h3>
          <span class="arrow">→</span>
        </a>
      </div>
    </div>
  </section>
</main>

<section class="cta-band">
  <div class="wrap">
    <span class="label">05 — <b>Hafa samband</b></span>
    <h2>Með verkefni í&nbsp;huga? Ekki hika við að hafa samband og við getum rætt málin saman&nbsp;☕</h2>
    <a class="alink" href="hafa-samband.html">Hafa samband</a>
  </div>
</section>
"""

page(
    "index.html",
    "ÍSDAL — Arkitektúr & innanhússhönnun í Reykjavík",
    "Ísdal er arkitekta- og hönnunarstofa í Reykjavík. Arkitektúr, innanhússhönnun og byggingarleyfi — frá fyrstu skissu að fullbúnu rými.",
    "heim",
    index_body,
)

# ------------------------------------------------------------------
# verkefni.html
# ------------------------------------------------------------------

verkefni_body = f"""
<main>
  <section class="page-head wrap">
    <span class="label"><b>Verkefni</b> — {len(PROJECTS)} verk</span>
    <h1 class="display">Verkefni</h1>
    <p class="lede">Frá sumarhúsum og eldhúsum til kvikmyndavera og skóla fyrir þúsund nemendur.</p>
  </section>
  <section class="section" style="padding-top: 0;">
    <div class="wrap">
      <div class="filterbar" role="group" aria-label="Sía verkefni">
        <button data-filter="allt" class="active">Allt</button>
        <button data-filter="arkitektur">Arkitektúr</button>
        <button data-filter="innanhus">Innanhússhönnun</button>
        <button data-filter="fyrri">Fyrri verkefni</button>
      </div>
      <div class="projects-grid">
        {''.join(pcard(pr, '') for pr in PROJECTS)}
      </div>
    </div>
  </section>
</main>
"""

page(
    "verkefni.html",
    "Verkefni — ÍSDAL",
    "Verkefni Ísdal: arkitektúr og innanhússhönnun — auk fyrri verka sem unnin voru hjá öðrum stofum.",
    "verkefni",
    verkefni_body,
)

# ------------------------------------------------------------------
# project detail pages
# ------------------------------------------------------------------

for i, pr in enumerate(PROJECTS):
    nxt = PROJECTS[(i + 1) % len(PROJECTS)]
    meta_rows = "".join(
        f'<div class="row"><span class="k">{k}</span><span class="v">{v}</span></div>'
        for k, v in pr["meta"]
    )
    paras = "".join(f"<p>{t}</p>" for t in pr["paras"])

    figs_html = []
    pending_two = []
    fig_i = 0

    def fig(src, cap, narrow=False):
        global fig_i
        fig_i += 1
        cls = ' class="narrow"' if narrow else ""
        return (
            f'<figure class="plate reveal"{cls}>'
            f'<img src="../assets/img/{src}" alt="{pr["title"]} — {cap}" loading="lazy">'
            f'<figcaption><span>Verk {pr["num"]} — Mynd {fig_i:02d}</span><span><b>{cap}</b></span></figcaption>'
            f"</figure>"
        )

    for src, cap, half in pr["figs"]:
        if half:
            pending_two.append(fig(src, cap))
            if len(pending_two) == 2:
                figs_html.append('<div class="two">' + "".join(pending_two) + "</div>")
                pending_two = []
        else:
            if pending_two:
                figs_html.append('<div class="two">' + "".join(pending_two) + "</div>")
                pending_two = []
            figs_html.append(fig(src, cap, narrow=True))
    if pending_two:
        figs_html.append('<div class="two">' + "".join(pending_two) + "</div>")

    detail_body = f"""
<main>
  <section class="detail-head wrap">
    <a class="label crumb" href="../verkefni.html">← Öll verkefni</a>
    <span class="label" style="display:block; margin-bottom:18px;">Verk {pr['num']} — <b>{pr['catlabel']}</b></span>
    <h1>{pr['title']}</h1>
  </section>
  <section class="section" style="padding-top:0;">
    <div class="wrap">
      <div class="detail-grid">
        <aside>
          <div class="meta-table">{meta_rows}</div>
        </aside>
        <div class="detail-body">
          <p class="lede">{pr['lede']}</p>
          {paras}
          <div class="figs">
            {''.join(figs_html)}
          </div>
        </div>
      </div>
      <div class="next-project reveal">
        <span class="label">Næsta verk — {nxt['num']}</span>
        <a href="{nxt['slug']}.html">{nxt['title']}</a>
      </div>
    </div>
  </section>
</main>
"""

    page(
        f"verkefni/{pr['slug']}.html",
        f"{pr['title']} — Verkefni — ÍSDAL",
        pr["lede"],
        "verkefni",
        detail_body,
        p="../",
    )

# ------------------------------------------------------------------
# team data + pages
# ------------------------------------------------------------------

TEAM = [
    {
        "slug": "hildur",
        "name": "Hildur Ísdal Þorgeirsdóttir",
        "role": "Stofnandi — Arkitekt &amp; innanhússhönnuður",
        "img": "hildur.webp",
        "init": "H",
        "paras": [
            "Hildur stofnaði Ísdal eftir rúman áratug á arkitektastofum í Stokkhólmi og Reykjavík. Ferillinn hófst í innanhússarkitektúr í Mílanó um aldamótin; síðan lá leiðin í arkitektúr við Listaháskóla Íslands og KTH í Stokkhólmi, þaðan sem hún útskrifaðist sem arkitekt árið 2014.",
            "Hún hefur unnið að öllu frá eldhúsum upp í háskólahverfi — og sú samsetning, detalja innanhússhönnuðarins og yfirsýn arkitektsins, mótar öll verkefni stofunnar. Hildur er löggiltur mannvirkjahönnuður og hannar hús jafnt að innan sem utan.",
        ],
        "cv": [
            ("2023–", "Ísdal — stofnandi og eigandi, Reykjavík"),
            ("2021–23", "Plús arkitektar, Reykjavík — arkitekt"),
            ("2017–21", "Arkitema, Stokkhólmi — arkitekt"),
            ("2014–17", "Cedervall arkitekter, Stokkhólmi — arkitekt"),
            ("2012", "White arkitekter, Stokkhólmi"),
            ("2003–12", "Innanhússhönnun, Reykjavík og Mílanó"),
            ("Menntun", "MS í sjálfbærum arkitektúr — KTH, Stokkhólmi · BA í arkitektúr — Listaháskóli Íslands · Innanhússhönnun — SPD Scuola Politecnica di Design, Mílanó · Löggiltur mannvirkjahönnuður"),
        ],
    },
    {
        "slug": "dagny",
        "name": "Dagný Björt Benjamínsdóttir",
        "role": "Innanhússarkitekt",
        "img": None,
        "init": "D",
        "paras": [
            "Dagný Björt er innanhússarkitekt með BA-gráðu frá IED í Barselóna og gekk til liðs við Ísdal haustið 2025. Hún er alin upp á Íslandi og sækir innblástur jafnt í íslenska náttúru og skandinavíska hönnunarhefð.",
            "Áður starfaði hún við eldhús- og innréttingahönnun hjá JKE Design, sem hönnunarráðgjafi hjá Módern og í starfsnámi hjá Fundació Enric Miralles í Barselóna. Hjá Ísdal vinnur hún að innanhússverkefnum stofunnar — innréttingum, efnisvali og lýsingu — og fylgir sérsmíði eftir frá teikningu að uppsetningu.",
        ],
        "cv": [
            ("2025–", "Ísdal — innanhússarkitekt, Reykjavík"),
            ("2024–26", "Módern — hönnunarráðgjafi, Reykjavík"),
            ("2023", "Fundació Enric Miralles, Barselóna — starfsnám"),
            ("2022–23", "JKE Design — innanhússhönnuður"),
            ("Menntun", "BA í innanhússhönnun — IED Istituto Europeo di Design, Barselóna"),
        ],
    },
    {
        "slug": "sara",
        "name": "Sara",
        "role": "Innanhússhönnuður",
        "img": None,
        "init": "S",
        "paras": [
            "Sara er innanhússhönnuður hjá Ísdal. Hún vinnur þvert á verkefni stofunnar að efnisvali, húsgögnum og framsetningu og heldur utan um efnissafn vinnustofunnar á Austurstræti.",
        ],
        "cv": [],
    },
]

for person in TEAM:
    if person["img"]:
        visual = f"""<figure class="plate reveal">
          <img src="../assets/img/{person['img']}" alt="{person['name']}">
          <figcaption><span><b>{person['name']}</b></span><span>Reykjavík</span></figcaption>
        </figure>"""
    else:
        visual = f"""<div class="ph-tile reveal">
          <span class="init">{person['init']}</span>
          <svg viewBox="0 0 24 24" fill="currentColor"><polygon points="0,9 24,0 24,24 0,24"/></svg>
        </div>"""

    cv_html = ""
    if person["cv"]:
        rows = "".join(
            f'<div class="row"><span class="k">{k}</span><span>{v}</span></div>'
            for k, v in person["cv"]
        )
        cv_html = f'<div class="cv">{rows}</div>'

    paras = "".join(f"<p>{t}</p>" for t in person["paras"])

    person_body = f"""
<main>
  <section class="detail-head wrap">
    <a class="label crumb" href="../um-okkur.html">← Um okkur</a>
    <span class="label" style="display:block; margin-bottom:18px;"><b>Teymið</b></span>
    <h1>{person['name']}</h1>
  </section>
  <section class="section" style="padding-top:0;">
    <div class="wrap">
      <div class="founder">
        {visual}
        <div>
          <span class="label role">{person['role']}</span>
          {paras}
          {cv_html}
        </div>
      </div>
    </div>
  </section>
</main>
"""
    page(
        f"folk/{person['slug']}.html",
        f"{person['name']} — ÍSDAL",
        f"{person['name']} — {person['role'].replace('&amp;', '&')} hjá Ísdal.",
        "um",
        person_body,
        p="../",
    )

# ------------------------------------------------------------------
# um-okkur.html
# ------------------------------------------------------------------


def tcard(person):
    if person["img"]:
        ph = f'<div class="ph"><img src="assets/img/{person["img"]}" alt="{person["name"]}"></div>'
    else:
        ph = f"""<div class="ph">
            <span class="init">{person['init']}</span>
            <svg viewBox="0 0 24 24" fill="currentColor"><polygon points="0,9 24,0 24,24 0,24"/></svg>
          </div>"""
    return f"""
        <a class="tcard reveal" href="folk/{person['slug']}.html">
          {ph}
          <div class="meta"><b>{person['name']}</b><span>{person['role']}</span></div>
        </a>"""


um_body = f"""
<main>
  <section class="page-head wrap">
    <span class="label"><b>Um okkur</b> — Stofan</span>
    <h1 class="display">Frá skissu til framkvæmdaloka</h1>
    <p class="lede">Ísdal er arkitekta- og hönnunarstofa í Reykjavík sem fylgir verkefnum alla leið — arkitektúr, innanhússhönnun og byggingarleyfi á einni hendi.</p>
  </section>

  <section class="section" style="padding-top:0;">
    <div class="wrap">
      <div class="section-head">
        <span class="label">01 — <b>Nálgun</b></span>
      </div>
      <div class="detail-grid">
        <div>
          <div class="studio-strip vert">
            <div><span class="big">20+</span><span class="label">Ára reynsla</span></div>
            <div><span class="big">15+</span><span class="label">Verkefni kláruð</span></div>
          </div>
        </div>
        <div class="detail-body">
          <p class="lede">Náttúrleg efni, birta og tímalaus hönnun — rými sköpuð utan um fólkið sem notar þau, með gæði út í gegn.</p>
          <p>Hvert verkefni byrjar á fólkinu: hvernig það lifir, hvernig gengið er um heimilið á venjulegum þriðjudegi og hvar dagsbirtan fellur. Út frá því mótum við rými utan um einstaklinginn — hönnun sem lyftir hversdagslegum athöfnum og gerir daglegt líf einfaldara og fallegra.</p>
          <p>Við veljum náttúrleg efni sem eldast vel — við, stein og ull — og vinnum markvisst með birtuna í hverju rými. Markmiðið er tímalaus hönnun: hús og innréttingar sem standast tísku og tíma jafn vel eftir tuttugu ár og á afhendingardegi.</p>
          <p>Gæði eru rauði þráðurinn í gegnum allt ferlið — í hugsun, teikningu, efnisvali og framkvæmd. Þess vegna fylgjum við verkefnum frá fyrstu skissu til framkvæmdaloka og teiknum detaljur niður í minnstu samskeyti.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <div class="section-head">
        <span class="label">02 — <b>Teymið</b></span>
        <span class="label muted">Smelltu á starfsmann fyrir nánari upplýsingar</span>
      </div>
      <div class="team-grid">
        {''.join(tcard(p) for p in TEAM)}
      </div>
    </div>
  </section>
</main>

<section class="cta-band">
  <div class="wrap">
    <span class="label">03 — <b>Samstarf</b></span>
    <h2>Viltu vinna með okkur — eða hjá okkur?</h2>
    <a class="alink" href="hafa-samband.html">Hafa samband</a>
  </div>
</section>
"""

page(
    "um-okkur.html",
    "Um okkur — ÍSDAL",
    "Ísdal er arkitekta- og hönnunarstofa í Reykjavík sem fylgir verkefnum frá fyrstu skissu til framkvæmdaloka.",
    "um",
    um_body,
)

# ------------------------------------------------------------------
# frettir.html
# ------------------------------------------------------------------

frettir_body = f"""
<main>
  <section class="page-head wrap">
    <span class="label"><b>Fréttir</b> — Af stofunni</span>
    <h1 class="display">Fréttir</h1>
  </section>
  <section class="section" style="padding-top:0;">
    <div class="wrap">
      <div class="news-list">
        <div class="news-item reveal">
          <time datetime="2026-08-01">01.08.2026</time>
          <div>
            <h3>Ný ásýnd og nýr vefur Ísdal</h3>
            <p>Nýtt merki, ný ásýnd og nýr vefur sem endurspeglar breiddina í verkefnum okkar — frá innréttingum til heildarskipulags. Merkið sækir form sitt í íslenska jökulinn sem stofan heitir eftir.</p>
          </div>
        </div>
        <div class="news-item reveal">
          <time datetime="2026-06-15">15.06.2026</time>
          <div>
            <h3>Sara innanhússhönnuður gengur til liðs við stofuna</h3>
            <p>Við bjóðum Söru innanhússhönnuð velkomna í teymið. Sara vinnur þvert á verkefni stofunnar að efnisvali, húsgögnum og framsetningu.</p>
          </div>
        </div>
        <div class="news-item reveal">
          <time datetime="2026-03-10">10.03.2026</time>
          <div>
            <h3>Ísdal opnar vinnustofu á Austurstræti 12a</h3>
            <p>Stofan hefur komið sér fyrir í bjartri vinnustofu á Austurstræti 12a, 101 Reykjavík. Kaffið er alltaf heitt — kíktu í heimsókn ef þú ert með verkefni í huga.</p>
          </div>
        </div>
        <a class="news-item reveal" href="{MBL_LAUGARDALUR}" target="_blank" rel="noopener">
          <time datetime="2025-11-18">18.11.2025</time>
          <div>
            <h3>„Hildur hannaði stórkostlegt eldhús í Reykjavík“</h3>
            <p>Morgunblaðið fjallar um eldhúsið í Laugardal — hús frá 1985 eftir Kjartan Sveinsson þar sem upprunalegi bleiki marmarinn fékk að halda sér. Lesa umfjöllunina á mbl.is.</p>
          </div>
          <span class="arrow">↗</span>
        </a>
        <div class="news-item reveal">
          <time datetime="2025-10-20">20.10.2025</time>
          <div>
            <h3>Dagný Björt innanhússarkitekt hefur störf hjá Ísdal</h3>
            <p>Dagný Björt Benjamínsdóttir innanhússarkitekt hóf störf hjá stofunni í október og styrkir innanhússteymið — innréttingar, efnisval og lýsingu í verkefnum stofunnar.</p>
          </div>
        </div>
        <a class="news-item reveal" href="{MBL_MOSFELLSBAER}" target="_blank" rel="noopener">
          <time datetime="2025-02-23">23.02.2025</time>
          <div>
            <h3>„Bogadreginn tangi kom í staðinn fyrir eyju“</h3>
            <p>Morgunblaðið fjallar um eldhúsið í Mosfellsbæ þar sem bogadreginn tangi leysti eyjuna af hólmi — og ræðir við Hildi um heimkomuna og stofnun Ísdal. Lesa umfjöllunina á mbl.is.</p>
          </div>
          <span class="arrow">↗</span>
        </a>
      </div>
    </div>
  </section>
</main>
"""

page(
    "frettir.html",
    "Fréttir — ÍSDAL",
    "Fréttir af Ísdal — arkitekta- og hönnunarstofu í Reykjavík.",
    "frettir",
    frettir_body,
)

# ------------------------------------------------------------------
# hafa-samband.html
# ------------------------------------------------------------------

samband_body = f"""
<main>
  <section class="page-head wrap">
    <span class="label"><b>Hafa samband</b></span>
    <h1 class="display">Segðu okkur frá verkefninu</h1>
    <p class="lede">Stórt eða smátt — við tökum vel á móti öllum hugmyndum. Fyrsta samtal er alltaf án skuldbindinga.</p>
  </section>
  <section class="section" style="padding-top:0;">
    <div class="wrap">
      <div class="contact-grid">
        <div>
          <div class="contact-list">
            <div class="row"><span class="k">Vinnustofa</span><span class="v">Austurstræti 12a<br>101 Reykjavík, Ísland</span></div>
            <div class="row"><span class="k">Instagram</span><span class="v"><a href="{INSTAGRAM}" target="_blank" rel="noopener">@hildur_isdal</a></span></div>
            <div class="row"><span class="k">LinkedIn</span><span class="v"><a href="{LINKEDIN}" target="_blank" rel="noopener">Hildur Ísdal</a></span></div>
          </div>
          <p class="muted" style="margin-top:28px; max-width:36em;">Við svörum fyrirspurnum að jafnaði innan tveggja virkra daga.</p>
        </div>
        <form class="contact-form" novalidate>
          <div class="field">
            <label for="nafn">Nafn</label>
            <input id="nafn" name="nafn" type="text" autocomplete="name" required>
          </div>
          <div class="field">
            <label for="netfang">Netfang</label>
            <input id="netfang" name="netfang" type="email" autocomplete="email" required>
          </div>
          <div class="field">
            <label for="skilabod">Skilaboð — segðu okkur aðeins frá verkefninu</label>
            <textarea id="skilabod" name="skilabod" rows="6" required></textarea>
          </div>
          <button type="submit">Senda fyrirspurn</button>
        </form>
      </div>
      <p class="contact-foot">Viltu frekar senda tölvupóst? Netfangið okkar er <a href="mailto:info@isdal.is">info@isdal.is</a>.</p>
    </div>
  </section>
</main>
"""

page(
    "hafa-samband.html",
    "Hafa samband — ÍSDAL",
    "Hafðu samband við Ísdal — Austurstræti 12a, 101 Reykjavík.",
    "samband",
    samband_body,
)

print("done.")
